version: '3.7'

services:
  ibm-mq:
    image: ibmcom/mq:latest
    container_name: ibm-mq
    restart: always
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=student
    ports:
      - "1414:1414"  # MQ pro klienty
      - "9443:9443"  # MQ Web UI
    volumes:
      - mqdata:/var/mqm

volumes:
  mqdata:
    driver: local
